# Generated by Django 4.2.23 on 2025-07-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
