# Generated by Django 4.2.23 on 2025-07-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
