# Generated by Django 4.2.23 on 2025-07-01 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_gid_employee_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='GID',
            new_name='GIN',
        ),
    ]
